### PR TITLE
Fix `slot` to return `bigint` when specified true for second argument

### LINKED ISSUE #466: slot tries to pack int64 into a JS Number
```
    if (argc == 2 && !!JS_ToBool(ctx, argv[1]))
        JS_FreeValue(ctx, *out);
        returnJS(data_as_int64(ptr, len));
```

I don't believe all int64 will pack into a JS Number

### PR DESCRIPTION
**Pull request by tequdev**
## High Level Overview of Change

fix #466

### Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (non-breaking change that only restructures code)
- [ ] Tests (you added tests for code that already exists, or your new feature included in this PR)
- [ ] Documentation update
- [ ] Chore (no impact to binary, e.g. `.gitignore`, formatting, dropping support for older tooling)
- [ ] Release

### API Impact

- [ ] Public API: New feature (new methods and/or new fields)
- [ ] Public API: Breaking change (in general, breaking changes should only impact the next api_version)
- [ ] `libxrpl` change (any change that may affect `libxrpl` or dependents of `libxrpl`)
- [ ] Peer protocol change (must be backward compatible or bump the peer protocol version)

### CODE REVIEW

File: src/ripple/app/hook/impl/applyHook.cpp [hunk 1]
```diff
@@ -3432,7 +3433,10 @@ DEFINE_JS_FUNCTION(JSValue, slot, JSValue raw_slot_no)
     if (argc == 2 && !!JS_ToBool(ctx, argv[1]))
     {
         JS_FreeValue(ctx, *out);
-        returnJS(data_as_int64(ptr, len));
+        int64_t data = data_as_int64(ptr, len);
```
Comment (sublimator) [inline src/ripple/app/hook/impl/applyHook.cpp:3436]: We definitely want a signed integer here, and not unsigned ? 
Is there any argument for unsigned?

WASM slot returns a signed integer, so it's inline with that at least

Comment (sublimator) [reply src/ripple/app/hook/impl/applyHook.cpp:3436]: This also leads to a discussion about JS vs WASM api convention adherence. The reason for existing is to make things easier.

Could change the api to `slot(n, 'uint64')` and `slot(n, 'int64')` ?

Comment (sublimator) [reply src/ripple/app/hook/impl/applyHook.cpp:3436]: Only tangentially related, I wonder why we aren't using JS_CLASS_UINT8_ARRAY, i.e. a typed array, as using an array of floats is a bit inefficient? 

https://github.com/Xahau/xahaud/issues/574

**Review by sublimator — APPROVED** [review]
