### PR TITLE
Fix Error handling on build action

### LINKED ISSUE #409: Github Action shows success for job even though build has error.
https://github.com/Xahau/xahaud/actions/runs/12267969413/job/34229365811?pr=318
スクリーンショット 2024-12-16 14 42 56

### PR DESCRIPTION
**Pull request by tequdev**
close #409 

Example of failure in build job.
https://github.com/Xahau/xahaud/actions/runs/12348238153/job/34456701369

### Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (non-breaking change that only restructures code)
- [ ] Tests (you added tests for code that already exists, or your new feature included in this PR)
- [ ] Documentation update
- [ ] Chore (no impact to binary, e.g. `.gitignore`, formatting, dropping support for older tooling)
- [ ] Release

### API Impact

- [ ] Public API: New feature (new methods and/or new fields)
- [ ] Public API: Breaking change (in general, breaking changes should only impact the next api_version)
- [ ] `libxrpl` change (any change that may affect `libxrpl` or dependents of `libxrpl`)
- [ ] Peer protocol change (must be backward compatible or bump the peer protocol version)

### CODE REVIEW

File: build-core.sh [hunk 1]
```diff
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+set -e
```
Comment (sublimator) [inline build-core.sh:3]: LGTM, and a huge step in the right direction, but also propose:

```
#!/bin/bash -u
# We use set -e and bash with -u to bail on first non zero exit code of any
# processes launched or upon any unbound variable.
# We use set -x to print commands before running them to help with
# debugging.
set -ex
```

Comment (tequdev) [reply build-core.sh:3]: I will add these after the current CI is finished.
